name: Keep Render Alive

on:
  schedule:
    - cron: '*/14 * * * *'  # 14分ごと実行

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          curl https://crystal-knowledge.onrender.com/api/posts/all
          echo "Pinged at $(date)"
